### ISSUE TITLE
Fix row naming convention

### ISSUE THREAD

**Issue by abresler** [sfeuerriegel/SentimentAnalysis#1]
First, great package already!  Very excited about where this can go, I love all of your teaching as well.  I think there is an issue with your intended row names for the `analyzeSentiment` function

```
analyzeSentiment(crude)
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  duplicate row.names: character(0)
```

The function itself works and return results, it just appears the row names aren't being assigned.

<img width="333" alt="screen shot 2016-06-27 at 9 00 43 am" src="https://cloud.githubusercontent.com/assets/740564/16380557/bc2030ca-3c45-11e6-97c4-1bc005dfbf3a.png">

**Comment by sfeuerriegel** [comment]
Just fixed that and added a unit test.
