### ISSUE TITLE
Will be sentiment analysis in other languages than English available?

### ISSUE THREAD

**Issue by rdatasculptor** [sfeuerriegel/SentimentAnalysis#2]
Great package!

Are you planning to add sentiment analysis possibilities for other languages than English? I am very interested in this possibility in Dutch, 

Kind regards,
Jelle

**Comment by sfeuerriegel** [comment]
Hi Jelle,

one of the next releases will make it possible to switch to other languages. However, one needs to have a dictionary for that language. Do you have a dictionary of positive/negative words in Dutch? 

Best, Stefan

**Comment by sfeuerriegel** [comment]
Hi Jelle,

I just have made a new push that now supports arbitrary language. The only "drawback" is that one must supply a dictionary for that language. This can be done in two ways:
- If you have a baseline / response variable, it's easy as you can generate a dictionary for that language. 
- If you haven't, then you need to collect positive/negative language from the language of your choice and store them in a SentimentDictionaryBinary object. You might find pre-sorted listed for Dutch only.

The vignette contains an example of how to do that for German.

Good luck, Stefan

**Comment by sfeuerriegel** [comment]
If you have wordlist, we could integrate in the package (if you want to). I hope this helps!

**Comment by rdatasculptor** [comment]
Dear Stefan,

I finally found a dutch sentiment wordlist. It can be found here: https://github.com/clips/pattern/blob/master/pattern/text/nl/nl-sentiment.xml
Do you think it can be added to your package? 
Ofcourse I also will try it myself to do that like the way you discribed in the vignette.

Best regards,
Jelle

**Comment by sfeuerriegel** [comment]
Dear Jelle,

that should be fairly straightforward. Just extract the Dutch words from the XML file and load them into R. Then you find an example (for German) in the vignette. 

Best, Stefan

**Comment by rdatasculptor** [comment]
Dear Stefan,

Maybe it sounds a bit silly, but where can I find the vignette? I do not
seem to be able to find any. I think I overlooked.

Kind regards,
jelle

2016-10-17 18:53 GMT+02:00 sfeuerriegel <notifications@github.com>:

**Comment by sfeuerriegel** [comment]
Here we go! 

https://github.com/sfeuerriegel/SentimentAnalysis/blob/master/vignettes/SentimentAnalysis.Rmd

**Comment by rdatasculptor** [comment]
thanks!

2016-10-17 23:13 GMT+02:00 sfeuerriegel notifications@github.com:

**Comment by rdatasculptor** [comment]
Your example seems to work! Thanks again. However when I try this with weighted words it throws errors.

This is what I do:

```
woorden <- c("goed","slecht")
scores <- c(0.8,-0.5)
nldb <- SentimentDictionaryWeighted(woorden,scores)
documents <- "dit is heel slecht"
sentiment <- analyzeSentiment(documents,
                              language="dutch",
                              rules=list("nedsentiment"=list(ruleSentiment, nldb)))
```

any ideas about what's going wrong?

**Comment by sfeuerriegel** [comment]
There is a slight modification necessary when working with sentiment scores (see code below). I have added this example also in the vignette.

```
woorden <- c("goed","slecht")
scores <- c(0.8,-0.5)
dictionaryDutch <- SentimentDictionaryWeighted(woorden, scores)
documents <- "dit is heel slecht"
sentiment <- analyzeSentiment(documents,
                              language="dutch",
                              rules=list("DutchSentiment"=list(ruleLinearModel, dictionaryDutch)))
sentiment
```
