### ISSUE TITLE
How to extend Support for other languages?

### ISSUE THREAD

**Issue by strategist922** [sfeuerriegel/SentimentAnalysis#3]
Dear Sir,

          Could this package can support other languages, such as Chinese, Japanese...?

          Or how can I extend this package to support other languages?

**Comment by sfeuerriegel** [comment]
Kindly see the following post which describes how you can make it work in Dutch as an example: #2. Moreover, the detailed vignette also includes another example for German. Kindly check if this applies to Asian languages (as I am not aware how that grammar works) and let me know if there are further change requests are necessary.

**Comment by strategist922** [comment]
Hi sfeuerriegel ,
    I have dictionery of Chinese Language(bot zh_CN and zh_TW) that include word attributes, for example 
postitive or negative...

   another Ref. (have 41 Laguages)
https://github.com/strategist922/NRC-Persian-Lexicon

**Comment by sfeuerriegel** [comment]
Kindly see #2 for an example.
