### ISSUE TITLE
Italian Dictionary

### ISSUE THREAD

**Issue by ms1948** [sfeuerriegel/SentimentAnalysis#5]
I should like to use SentimentAnalysis package with a Dictionary in italian language.
How can I do it ?

Thanks

**Comment by sfeuerriegel** [comment]
The vignette contains an example for both German and Dutch, but it can be extended to Italian:
https://github.com/sfeuerriegel/SentimentAnalysis/blob/master/vignettes/SentimentAnalysis.Rmd#language-support-and-extensibility
In any case, you will need to develop a dictionary for your desired language.

**Comment by ms1948** [comment]
Thanks a lot
