### ISSUE TITLE
Test statistic being displayed instead of p-value

### ISSUE THREAD

**Issue by abendorf** [sfeuerriegel/SentimentAnalysis#6]
Hello,

  There is a typo in analyzeSentiment.R that is causing compareToResponse to show an incorrect cor.p.value.  Note, for example, that the example compareToResponse output in the Readme shows the same value for cor.t.statistic and cor.p.value, which is obviously incorrect:
#>                              WordCount SentimentGI NegativityGI
#> cor                        -0.18569534   0.9900115  -0.99748901
#> cor.t.statistic            -0.37796447  14.0440465 -28.16913204
#> cor.p.value                -0.37796447  14.0440465 -28.16913204
  
  The problem is in line 321 of analyzeSentiment.R.  Currently, the line is the following:
`"cor.p.value"=unlist(lapply(colnames(sentiment), function(x) cor.test(sentiment[, x], response)$statistic)),`

I believe that this should instead read

`"cor.p.value"=unlist(lapply(colnames(sentiment), function(x) cor.test(sentiment[, x], response)$p.val)),
`

Best,
Adam

**Comment by sfeuerriegel** [comment]
Thanks for letting me now. The code is fixed on GitHub and the updated package will become available shortly on CRAN.
